name: Analyze PGN

on:
  workflow_dispatch:
    inputs:
      pgn_file:
        description: 'Nazwa pliku PGN'
        required: true
        default: 'merged_.pgn'
      total_jobs:
        description: 'Ile jobow'
        required: true
        default: '20'
      total_games:
        description: 'Ile gier w pliku'
        required: true
        default: '600'
      depth:
        description: 'Glebokosc analizy'
        required: true
        default: '10'

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev
          python3 -m pip install --upgrade pip
          pip install chess

      - name: Make engine executable
        run: chmod +x engines/ethereal/Ethereal

      - name: Run analysis
        run: |
          python main.py --pgn ${{ github.event.inputs.pgn_file }} --job-id ${{ matrix.job_id }} --total-jobs ${{ github.event.inputs.total_jobs }} --total-games ${{ github.event.inputs.total_games }} --depth ${{ github.event.inputs.depth }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: acpl-job-${{ matrix.job_id }}
          path: acpl_job_${{ matrix.job_id }}.csv
