name: Chess Engine Tests

on:
  workflow_dispatch:
    inputs:
      games_per_job:
        description: 'Liczba gier na zadanie'
        required: true
        default: '5'
      depth:
        description: 'Glebokosc'
        required: true
        default: 3

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        job_id: [7, 8]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python config
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tests start
        run: |
          OFFSET=$(( ( ${{ matrix.job_id }} - 1 ) * ${{ github.event.inputs.games_per_job }} ))
          python main.py --games ${{ github.event.inputs.games_per_job }} --depth ${{ github.event.inputs.depth }} --job-id ${{ matrix.job_id }} --offset $OFFSET
        shell: bash

      - name: Send results
        uses: actions/upload-artifact@v4
        with:
          name: wyniki-${{ matrix.job_id }}
          path: depth_${{ matrix.job_id }}.pgn
