name: Chess Engine Tests

on:
  workflow_dispatch:
    inputs:
      games_per_job:
        description: 'Liczba gier na zadanie'
        required: true
        default: '5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python config
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download and unpack Stockfish
        run: |
          mkdir -p engines
          wget -O stockfish.tar https://github.com/official-stockfish/Stockfish/releases/download/sf_16/stockfish-ubuntu-x86-64-avx2.tar
          tar -xf stockfish.tar -C engines
          chmod +x engines/stockfish

      - name: Ensure engines are executable
        run: chmod +x engines/*.exe engines/lc0/lc0.exe

      - name: Tests start
        run: |
          python main.py --games ${{ github.event.inputs.games_per_job }} --job-id ${{ matrix.job_id }}

      - name: Send results
        uses: actions/upload-artifact@v4
        with:
          name: wyniki-${{ matrix.job_id }}
          path: games_nnue_${{ matrix.job_id }}.pgn
