name: Chess Engine Tests

on:
  workflow_dispatch:
    inputs:
      games_per_job:
        description: 'Liczba gier na zadanie'
        required: true
        default: '5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python config
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download engines
        run: |
          mkdir -p engines
          wget -O engines/stockfish https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar
          wget -O engines/lc0 https://github.com/LeelaChessZero/lc0/releases/download/v0.31.2/lc0-v0.31.2-windows-gpu-nvidia-cudnn.zip
          chmod +x engines/*

      - name: Tests start
        run: |
          python main.py --games ${{ github.event.inputs.games_per_job }} --job-id ${{ matrix.job_id }}

      - name: Send results
        uses: actions/upload-artifact@v3
        with:
          name: wyniki-${{ matrix.job_id }}
          path: games_nnue_${{ matrix.job_id }}.pgn
