name: Chess Engine Benchmark

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python config
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tests start
        run: |
          python main.py --job-id ${{ matrix.job_id }}
        shell: bash

      - name: Send results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: results_${{ matrix.job_id }}.csv
